version: "3.8"

services:
  zentao:
    image: easysoft/zentao:12.3.3
    container_name: zentao
    platform: linux/amd64
    environment:
      - ZENTAO_VER=12.3.stable
      - BIND_ADDRESS=false
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ~/mydata/zentao/zentaopms:/www/zentaopms
      - ~/mydata/zentao/mysql-data:/var/lib/mysql
    ports:
      - "8060:80"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.services.zentao.loadbalancer.server.port=80"
      - "traefik.http.routers.zentao.rule=Host(`pm.nexuslearning.org`)"
      - "traefik.http.routers.zentao.entrypoints=websecure"
      - "traefik.http.routers.zentao.tls.certresolver=default-resolver"
    restart: always

networks:
  traefik-net:
    external: true